# Generated by Django 5.1.7 on 2025-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('nome_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
